controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    new_robot_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


simple_velocity_controller:
  ros__parameters:
    joints:
      - base_left_wheel_joint
      - base_right_wheel_joint